name: Lint commit messages
on:
  push:
    branches:
      - main
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@456526eec71276a59e74aafdfe06a9632ac2eee1 # v5.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
