name: Lint commit messages
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
  pull_request:
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@253ae1c7da064c079b5ab8f002983ebdea49ea89 # v4.1.2
    with:
      configFile: ./commitlint.config.cjs
