name: Lint commit messages
on:
  push:
    branches:
      - main
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          fetch-depth: 0
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@d6f6593a4762bd5aa8ffb0f60127f779aca3759d # tag=v5.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
